theme: minima
title: Les nacos
author: Novia Tjahjadi
email: rvalstrui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We will help you to organize, share and update 24/7 of RSVP's guess for your Big day!

# social links
twitter_username: nopitjahjadi # DO NOT include the @ character, or else the build will fail!
github_username:  valstrui # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
